### ISSUE TITLE
Chain Snapshots to establish holders

### ISSUE THREAD

**Issue by 2xJDubs** [dcdao/pink-airdrop-snapshot#1]
- [x] List of accounts that had at least 1 RING in stake or deposit on the start of the day October 11th, 2023 00:01.  Please include amount.
- [x] List of accounts that had at least 0.01 KTON in stake on the start of the day September 26th, 2023 00:01.  Please include amount.
- [x] List of accounts and amount of RING in stake or deposit for each account on 23rd January 2024, 16:51 UTC.
- [x] List of accounts and amount of KTON in stake for each account on 23rd January 2024, 16:51 UTC.

**Comment by acgxv** [comment]
Close via https://github.com/dcdao/pink-airdrop-snapshot/commit/7ce85bf9d98d6568067e7b4e7d19ea9bdbfb1ab7.
