### ISSUE TITLE
Eligibility criteria

### ISSUE THREAD

**Issue by aurexav** [dcdao/pink-airdrop-snapshot#2]

**Comment by 2xJDubs** [comment]
The October 11th, 2023 list for both RING and KTON will establish eligibility and the January 23rd, 2024 list for both will determine the amount of $PINK rewarded.  The results of the snapshot should produce two lists, one for RING and one for KTON where eligible accounts are noted in the list only if they still had RING or KTON on January 23rd.

For example:

If address A appears on the list October 11, 2023 they are eligible for the reward but on the January 23rd, 2024 list they hold 0 of the coin then they will receive 0 PINK.  This will be true for the RING and KTON lists.

**Comment by acgxv** [comment]
1. Retrieve and select valid RING accounts.
2. Retrieve and select valid KTON accounts.
3. Merge 1 and 2; accounts exclusive to list 1 will display as RING:x, KTON:0, whereas accounts in both lists will show as RING:x, KTON:x.
4. Generate the final list(who: PINK amount) based on step 3.
